{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "service.fullname" . }}
  namespace: {{ include "service.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ .Values.service.name }}
    app.kubernetes.io/instance: {{ include "service.fullname" . }}
    app.kubernetes.io/environment: {{ .Values.env }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ include "service.hostname" . }}
    cert-manager.io/cluster-issuer: letsencrypt-prod
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  tls:
    - hosts:
        - {{ include "service.hostname" . }}
      secretName: {{ include "service.fullname" . }}-tls
  rules:
    - host: {{ include "service.hostname" . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "service.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}